# Generated by Django 6.0.7 on 2026-08-16 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_perfil_c_alturas_alter_perfil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('s_generales', 'auxiliar de servicios generales'), ('jardineria', 'Realizar actividades de jardineria'), ('electricista', 'electrico'), ('ornamentacion', 'Trabajos de ornamentacion'), ('a_techos', 'Arreglo de techos'), ('pintura', 'Labores de pintura'), ('rastrillo', 'realizar actividades de rastrillo'), ('evento', 'Realizar apoyo en evento'), ('vidrios', 'Realizar limpieza de vidrios')], default='s_generales')),
                ('descripcion', models.CharField(max_length=600)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('e_proceso', 'En proceso'), ('culminada', 'Tarea Finalizada')], default='p_hacer')),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
    ]
