# Generated by Django 6.0.7 on 2026-08-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='c_alturas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('s_generales', 'auxiliar de servicios generales'), ('electricista', 'Actividades de electricidad'), ('Jardinero', 'Realizar actividades de jardineria'), ('RESPEL', 'Realizar actividades de recoleccion de residuos peligrosos'), ('reciclaje', 'Realizar actividades de reciclaje'), ('plomero', 'Realizar actividades de plomeria'), ('aux_c_taller', 'Auxiliar de casa taller')], default='s_generales', null=True),
        ),
    ]
