# Generated by Django 6.0.7 on 2026-08-09 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_documento', models.IntegerField()),
                ('r_fisica', models.BooleanField(default=False, null=True)),
                ('firma', models.ImageField(upload_to='')),
                ('zona_encargada', models.CharField(max_length=250, null=True)),
                ('rol', models.CharField(choices=[('s_generales', 'auxiliar de servicios generales'), ('jardineria', 'jardinero(a)'), ('electricista', 'electrico'), ('c_taller', 'Auxiliarn servicios de casa taller'), ('a_techos', 'Arreglo de techos')], default='s_generales', null=True)),
                ('clave', models.IntegerField()),
                ('apariencia', models.CharField(choices=[('dark', 'pink, purple, black'), ('claro', 'purple, blue')], default='claro')),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
