# Generated by Django 6.0.7 on 2026-08-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
